apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 4e4d4fad-1ada-4f29-92b5-0d62c3449cf5
    subject: git-test_litmus
    workflow_id: 34faeb09-1b0b-49e8-910a-f69a7a794d71
    workflows.argoproj.io/controller-instanceid: 4e4d4fad-1ada-4f29-92b5-0d62c3449cf5
  name: git-test-1656446127
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-network-latency-5e1
        template: pod-network-latency-5e1
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f /tmp/pod-network-latency-5e1.yaml -n {{workflow.parameters.adminModeNamespace}}
        |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-network-latency-5e1
        path: /tmp/pod-network-latency-5e1.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects network latency on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-network-latency
              labels:
                name: pod-network-latency
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.8.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - ""
                    resources:
                      - pods/exec
                    verbs:
                      - get
                      - list
                      - create
                  - apiGroups:
                      - apps
                    resources:
                      - deployments
                      - statefulsets
                      - replicasets
                      - daemonsets
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - apps.openshift.io
                    resources:
                      - deploymentconfigs
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - ""
                    resources:
                      - replicationcontrollers
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - argoproj.io
                    resources:
                      - rollouts
                    verbs:
                      - list
                      - get
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:2.8.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-network-latency
                command:
                  - /bin/bash
                env:
                  - name: TARGET_CONTAINER
                    value: ""
                  - name: NETWORK_INTERFACE
                    value: eth0
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.8.0
                  - name: TC_IMAGE
                    value: gaiadocker/iproute2
                  - name: NETWORK_LATENCY
                    value: "2000"
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: JITTER
                    value: "0"
                  - name: LIB
                    value: litmus
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: TARGET_PODS
                    value: ""
                  - name: CONTAINER_RUNTIME
                    value: docker
                  - name: DESTINATION_IPS
                    value: ""
                  - name: DESTINATION_HOSTS
                    value: ""
                  - name: SOCKET_PATH
                    value: /var/run/docker.sock
                  - name: NODE_LABEL
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-network-latency
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/runtime-api-usage: "true"
                  app.kubernetes.io/version: 2.8.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-network-latency-5e1.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:2.8.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-network-latency-5e1
        path: /tmp/chaosengine-pod-network-latency-5e1.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-network-latency-5e1
              labels:
                instance_id: a808ddb4-d9a7-4c6e-961d-1eefa6482099
                context: pod-network-latency-5e1_litmus
                workflow_name: git-test-1656446127
            spec:
              engineState: active
              appinfo:
                appns: bank
                applabel: app=frontend
                appkind: deployment
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-network-latency
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: NETWORK_LATENCY
                          value: "10000"
                        - name: JITTER
                          value: "0"
                        - name: CONTAINER_RUNTIME
                          value: docker
                        - name: SOCKET_PATH
                          value: /var/run/docker.sock
                        - name: PODS_AFFECTED_PERC
                          value: ""
                    probe: []
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-network-latency-5e1
    outputs: {}
  - container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (a808ddb4-d9a7-4c6e-961d-1eefa6482099,
        )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
